const os = require(`node:os`)
//los modulos de nodejs se puden utilizar con mjs o js
console.log(`Informacion del sistema operativo`)
console.log(`---------------------`)
console.log(`Nombre del sistema`,os.platform())
console.log(`---------------------`)
console.log(`Version del sistema`,os.release())
console.log(`---------------------`)
console.log(`Arquitectura del sistema`,os.arch())
console.log(`---------------------`)
console.log(`CPU`,os.cpus())
console.log(`---------------------`)
console.log(`Memoria libre`,os.freemem() / 1024 / 1024)
console.log(`Memoria total`,os.totalmem() / 1024 / 1024)
console.log(`Tiempo encendido`, os.uptime() / 60 / 60)